### ISSUE TITLE
Missing case: ImportSpecifier

### ISSUE THREAD

**Issue by fschopp** [unassert-js/babel-plugin-unassert#9]
The following import statement is currently not removed, even though it should:
```javascript
import { strict as assert } from 'assert';
```
See also [this StackOverflow question](https://stackoverflow.com/q/39883960).

The fix should be easy, change
```javascript
if (!(firstSpecifier.isImportDefaultSpecifier() || firstSpecifier.isImportNamespaceSpecifier())) {
```
to
```javascript
if (!(firstSpecifier.isImportDefaultSpecifier() || firstSpecifier.isImportNamespaceSpecifier() ||
    firstSpecifier.isImportSpecifier())) {
```

**Comment by twada** [comment]
Released as [babel-plugin-unassert 3.0.1](https://github.com/unassert-js/babel-plugin-unassert/blob/master/CHANGELOG.md#301-2019-05-14). Thanks @fschopp!
